#!/usr/bin/env python3
"""Build a portable .nrm package without changing the game or its generated code."""
import argparse
import json
from pathlib import Path
import subprocess
import tomllib
import zipfile

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path)
    parser.add_argument("--clang", default="clang")
    parser.add_argument("--linker", default="ld.lld")
    parser.add_argument("--tool", type=Path, required=True)
    parser.add_argument("--symbols", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("build/mods"))
    parser.add_argument("--wsl", action="store_true", help="Use Clang and LLD in Ubuntu-24.04 on Windows")
    parser.add_argument("--wsl-distro", default="Ubuntu-24.04")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    project = args.project.resolve()
    output = args.output.resolve()
    source = project / "mod.toml"
    manifest = tomllib.loads(source.read_text(encoding="utf-8"))
    mod_id = manifest["manifest"]["id"]
    work = output / mod_id
    work.mkdir(parents=True, exist_ok=True)
    def compile_command(command):
        if args.wsl:
            def linux_path(value):
                if len(value) > 2 and value[1] == ":":
                    return "/mnt/" + value[0].lower() + value[2:].replace("\\", "/")
                return value
            command = ["wsl", "-d", args.wsl_distro, "--", *map(linux_path, command)]
        subprocess.run(command, check=True)
    objects = []
    for c in sorted(project.glob("*.c")):
        obj = work / (c.stem + ".o")
        compile_command([args.clang, "-target", "mips", "-mips2", "-mabi=32", "-O2", "-G0",
            "-mno-abicalls", "-mno-odd-spreg", "-mno-check-zero-division", "-fomit-frame-pointer",
            "-fno-builtin", "-ffreestanding", "-nostdinc", "-ffunction-sections", "-Wall", "-Wextra", "-Werror",
            "-I", str(root / "modding/include"), "-c", str(c), "-o", str(obj)])
        objects.append(str(obj))
    if not objects:
        parser.error("Project has no .c files")
    elf = work / "mod.elf"
    compile_command([args.linker, "-nostdlib", "-T", str(root / "modding/mod.ld"),
        "--unresolved-symbols=ignore-all", "--emit-relocs", "-e", "0", "--no-nmagic", "--gc-sections",
        "-o", str(elf), *objects])
    additional = [p.resolve().as_posix() for p in (project / "rocket.json", project / "thumb.png") if p.is_file()]
    config = source.read_text(encoding="utf-8") + "\n[inputs]\n" + "\n".join(
        key + " = " + json.dumps(value) for key, value in {
            "elf_path": elf.as_posix(), "mod_filename": mod_id,
            "func_reference_syms_file": args.symbols.resolve().as_posix(),
            "data_reference_syms_files": [], "additional_files": additional}.items()) + "\n"
    config_path = work / "build.toml"
    config_path.write_text(config, encoding="utf-8")
    subprocess.run([str(args.tool.resolve()), str(config_path), str(work)], check=True)
    # Stable ZIP metadata makes profile hashes independent of build time.
    with zipfile.ZipFile(work / (mod_id + ".nrm")) as source_zip:
        with zipfile.ZipFile(output / (mod_id + ".nrm"), "w", compression=zipfile.ZIP_DEFLATED) as destination:
            for name in sorted(source_zip.namelist()):
                info = zipfile.ZipInfo(name, (2026, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                destination.writestr(info, source_zip.read(name))
    if mod_id == "rocket_modern_camera":
        payload = (output / (mod_id + ".nrm")).read_bytes()
        header = root / "generated/mod_camera.generated.hpp"
        header.parent.mkdir(parents=True, exist_ok=True)
        header.write_text("// Generated by scripts/build_mod.py.\n#pragma once\n#include <cstdint>\n"
            "namespace rocket::generated {\ninline constexpr std::uint8_t kCameraMod[] = {\n" +
            "\n".join(",".join(str(b) for b in payload[i:i+32])+"," for i in range(0,len(payload),32)) +
            "\n};\n}\n", encoding="utf-8")
    print(output / (mod_id + ".nrm"))

if __name__ == "__main__":
    main()
